import { AppTemplate } from 'app/components/templates/AppTemplate'
import { AOS } from 'app/components/ui/AOS'
import { AppData } from 'app/types/app'
import fs from 'fs/promises'
import type { Metadata } from 'next'
import { Geist } from 'next/font/google'
import path from 'path'
import './globals.css'

const nataSans = Geist({
  variable: '--font-sans',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const filePath = path.join(process.cwd(), 'src/data/appData.json')
  const jsonData = await fs.readFile(filePath, 'utf-8')
  const appData: AppData = JSON.parse(jsonData)
  return (
    <html lang="en">
      <body className={`${nataSans.variable} antialiased`}>
        <AOS />
        <AppTemplate data={appData}>{children}</AppTemplate>
      </body>
    </html>
  )
}
