import { AppTemplate } from 'app/components/templates/AppTemplate'
import { AOS } from 'app/components/ui/AOS'
import type { Metadata } from 'next'
import { Geist } from 'next/font/google'
import './globals.css'

const nataSans = Geist({
  variable: '--font-sans',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${nataSans.variable} antialiased`}>
        <AOS />
        <AppTemplate>{children}</AppTemplate>
      </body>
    </html>
  )
}
